- hosts: all
  vars_prompt: 
    - name: y
      private: no
      prompt: "enter the source location from where you want to copy file"
    - name: x
      private: no
      prompt: "enter the destination where to store file : "
  tasks: 
     - copy:
           dest: "{{ x }}"
           src: "{{ y }}"
