- hosts: all
  vars_files:
        - i_touch_ansible.yml
#  vars_prompt:
#     - name: x
#       prompt: "enter the port number of service"
#       private: no
  tasks:
  - firewalld:
      state: enabled
      port: "{{ x }}" 
      immediate: yes
      permanent: yes
