- hosts: all
  vars_files:
        - i_touch_ansible.yml
#  vars_prompt:
#     - name: x
#       prompt: "give name of vg"
#       private: no
#     - name: y
#       prompt: "give name of lv"
#       private: no
  tasks:
     - lvol:
         vg: "{{ x }}"
         lv: "{{ y }}"
         size: "{{ z }}"	# 100%PVS
         resizefs: true
         force: yes
