- hosts: localhost
  vars_files:
        - i_touch_ansible.yml
#  vars_prompt:
#     - name: x
#       prompt: "enter the file path where u want it to create"
#       private: no
#     - name: c
#       prompt: "enter the content to be given to file "
#       private: no
  tasks:
    - name: Ansible File Creation 
      file:
        path: "{{ x }}"
        state: touch
    - copy:
        content: "{{ y }}"
        dest: "{{ x }}"
